# Generated by Django 6.0.2 on 2026-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('tech_services', 'Tech Services'), ('creative_services', 'Creative Services'), ('home_services', 'Home Services'), ('education', 'Education'), ('health_wellness', 'Health & Wellness'), ('financial_services', 'Financial Services'), ('business_services', 'Business Services'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
