# Generated by Django 6.0.2 on 2026-04-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_lat_lng_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rate_type',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('flat', 'Flat Rate')], default='hour', max_length=4),
        ),
    ]
